-- 1
SELECT F.NOME, F.ANO 
FROM FILMES F 

-- 2
SELECT F.NOME, F.ANO, F.DURACAO  
FROM FILMES F 
ORDER BY F.ANO 

-- 3
SELECT F.NOME, F.ANO, F.DURACAO  
FROM FILMES F 
WHERE F.NOME = 'De Volta para o Futuro'

-- 4
SELECT F.NOME, F.ANO, F.DURACAO  
FROM FILMES F 
WHERE F.ANO = 1997

-- 5
SELECT F.NOME, F.ANO, F.DURACAO  
FROM FILMES F 
WHERE F.ANO > 2000

-- 6
SELECT F.NOME, F.ANO, F.DURACAO  
FROM FILMES F 
WHERE F.DURACAO > 100 AND f.DURACAO < 150 
ORDER BY F.DURACAO 

-- 7
SELECT F.ANO, COUNT(*) AS QUANTIDADE  
FROM FILMES F 
GROUP BY F.ANO 
ORDER BY QUANTIDADE DESC

-- 8
SELECT * 
FROM ATORES A 
WHERE A.GENERO = 'M'

-- 9
SELECT * 
FROM ATORES A 
WHERE A.GENERO = 'F' 
ORDER BY A.PRIMEIRONOME 

-- 10
SELECT F.NOME, G.GENERO  
FROM FILMES F 
INNER JOIN FILMESGENERO FG ON F.ID = FG.IDFILME 
INNER JOIN GENEROS G ON G.ID = FG.IDGENERO 

-- 11
SELECT F.NOME, G.GENERO  
FROM FILMES F 
INNER JOIN FILMESGENERO FG ON F.ID = FG.IDFILME 
INNER JOIN GENEROS G ON G.ID = FG.IDGENERO 
WHERE G.GENERO = 'Mistério'

-- 12
SELECT F.NOME, A.PRIMEIRONOME, A.ULTIMONOME, E.PAPEL 
FROM FILMES F 
INNER JOIN ELENCOFILME E ON F.ID = E.IDFILME 
INNER JOIN ATORES A ON A.ID = E.IDATOR 
